[package]
name = "circuit"
type = "bin"
authors = [""]
compiler_version = ">=0.33.0"

[dependencies]
noir_rsa = { path = "../../noir_rsa/lib" }
string_search = { tag = "v0.1", git = "https://github.com/noir-lang/noir_string_search"  }
