[package]
name = "circuit"
type = "bin"
authors = [""]
compiler_version = ">=0.32.0"

[dependencies]
noir_rsa = { tag = "v0.3", git = "https://github.com/noir-lang/noir_rsa" }
string_search = { path = "../../noir_string_search" }
