[package]
name = "stealthnote_jwt"
type = "bin"
authors = ["saleel"]
compiler_version = ">=0.38.0"
version = "0.2.0"

[dependencies]
# jwt = { tag = "v0.2.0", git = "https://github.com/saleel/noir-jwt" }
jwt = { path = "../../noir-jwt" }
string_search = { git = "https://github.com/olehmisar/noir_string_search", tag = "v0.3.0" } # switch to noir-org when 0.36.0 is merged
