name: Cron Job

on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call API endpoint
        run: |
          curl -X GET https://stealthnote.xyz/api/twitter 